/**
 * Question bank. The FIRST answer in each `a` array is the correct one; the game shuffles them.
 * c = topic ("Ghana" | "Africa" | "World")
 * l = level: "kids" (ages ~5-10), "all" (family), "adults"
 * why = optional short explanation shown after answering
 */
export const QUESTIONS = [
  // ---------------------------------------------------------------- Ghana
  { c: "Ghana", l: "kids", q: "What is the capital city of Ghana?", a: ["Accra", "Kumasi", "Tamale", "Cape Coast"] },
  { c: "Ghana", l: "kids", q: "What colour is the star in the middle of Ghana's flag?", a: ["Black", "Red", "Gold", "Green"], why: "The Black Star stands for African freedom." },
  { c: "Ghana", l: "kids", q: "What is Ghana's national football team called?", a: ["The Black Stars", "The Super Eagles", "The Indomitable Lions", "The Pharaohs"] },
  { c: "Ghana", l: "kids", q: "What does “Akwaaba” mean in Twi?", a: ["Welcome", "Goodbye", "Thank you", "Good morning"] },
  { c: "Ghana", l: "kids", q: "What money do people use in Ghana?", a: ["The cedi", "The naira", "The shilling", "The rand"] },
  { c: "Ghana", l: "kids", q: "Ghana grows lots of which crop, used to make chocolate?", a: ["Cocoa", "Sugar cane", "Vanilla", "Peanuts"] },
  { c: "Ghana", l: "kids", q: "Which spicy fried snack is made from ripe plantain?", a: ["Kelewele", "Sushi", "Tacos", "Falafel"] },
  { c: "Ghana", l: "kids", q: "Which country is directly east of Ghana?", a: ["Togo", "Burkina Faso", "Côte d'Ivoire", "Nigeria"] },
  { c: "Ghana", l: "all", q: "In which year did Ghana become independent?", a: ["1957", "1960", "1948", "1966"], why: "Ghana was the first sub-Saharan African country to gain independence from colonial rule." },
  { c: "Ghana", l: "all", q: "Who was Ghana's first president?", a: ["Kwame Nkrumah", "Jerry Rawlings", "John Kufuor", "Kofi Busia"] },
  { c: "Ghana", l: "all", q: "Lake Volta in Ghana is the world's largest artificial lake by what measure?", a: ["Surface area", "Depth", "Age", "Saltiness"], why: "Created by the Akosombo Dam, it covers roughly 8,500 square kilometres." },
  { c: "Ghana", l: "all", q: "Which Ghanaian diplomat became Secretary-General of the United Nations?", a: ["Kofi Annan", "Ban Ki-moon", "Boutros Boutros-Ghali", "Javier Pérez de Cuéllar"] },
  { c: "Ghana", l: "all", q: "What is Ghana's highest mountain?", a: ["Mount Afadjato", "Mount Kilimanjaro", "Mount Cameroon", "Mount Kenya"] },
  { c: "Ghana", l: "all", q: "Kumasi is the capital of which region?", a: ["Ashanti", "Volta", "Northern", "Western"] },
  { c: "Ghana", l: "all", q: "Which of these is a UNESCO World Heritage Site in Ghana?", a: ["Cape Coast Castle", "Great Zimbabwe", "Robben Island", "Fort Jesus"] },
  { c: "Ghana", l: "all", q: "Which brightly woven cloth is famous in Ghana?", a: ["Kente", "Ankara", "Kitenge", "Shweshwe"] },
  { c: "Ghana", l: "all", q: "The Adinkra symbol “Sankofa” reminds us to…", a: ["Learn from the past", "Save for tomorrow", "Respect the moon", "Work in a group"], why: "Sankofa is often translated as “go back and get it”." },
  { c: "Ghana", l: "all", q: "On which date is Ghana's Independence Day?", a: ["6 March", "1 July", "25 May", "4 April"] },
  { c: "Ghana", l: "all", q: "What gives Jollof rice its red colour?", a: ["Tomatoes", "Beetroot", "Cranberries", "Red cabbage"] },
  { c: "Ghana", l: "all", q: "Fufu in Ghana is traditionally eaten with…", a: ["Soup", "Salad", "Cereal", "Ice cream"] },
  { c: "Ghana", l: "adults", q: "What was Ghana called before independence?", a: ["The Gold Coast", "The Ivory Coast", "The Grain Coast", "The Slave Coast"] },
  { c: "Ghana", l: "adults", q: "The Akosombo Dam sits on which river?", a: ["The Volta", "The Niger", "The Congo", "The Zambezi"] },
  { c: "Ghana", l: "adults", q: "Which Ghanaian striker scored for the Black Stars at the 2006, 2010 and 2014 World Cups?", a: ["Asamoah Gyan", "Michael Essien", "Abedi Pele", "Stephen Appiah"] },
  { c: "Ghana", l: "adults", q: "Which Ghanaian leader founded the Convention People's Party?", a: ["Kwame Nkrumah", "J. B. Danquah", "Hilla Limann", "Kofi Busia"] },

  // --------------------------------------------------------------- Africa
  { c: "Africa", l: "kids", q: "What is the longest river in Africa?", a: ["The Nile", "The Congo", "The Niger", "The Zambezi"] },
  { c: "Africa", l: "kids", q: "Which is the biggest hot desert in the world?", a: ["The Sahara", "The Kalahari", "The Namib", "The Gobi"] },
  { c: "Africa", l: "kids", q: "Which animal is the tallest in the world?", a: ["Giraffe", "Elephant", "Lion", "Zebra"] },
  { c: "Africa", l: "kids", q: "Which animal is the fastest on land?", a: ["Cheetah", "Lion", "Horse", "Rhino"] },
  { c: "Africa", l: "kids", q: "Which big cat is known as the “king of the jungle”?", a: ["Lion", "Leopard", "Cheetah", "Tiger"] },
  { c: "Africa", l: "kids", q: "Which is the biggest land animal?", a: ["African elephant", "Hippo", "Giraffe", "Rhino"] },
  { c: "Africa", l: "all", q: "What is the highest mountain in Africa?", a: ["Mount Kilimanjaro", "Mount Kenya", "Mount Stanley", "Mount Elgon"] },
  { c: "Africa", l: "all", q: "What is the capital of Kenya?", a: ["Nairobi", "Mombasa", "Kampala", "Dodoma"] },
  { c: "Africa", l: "all", q: "What is the capital of Nigeria?", a: ["Abuja", "Lagos", "Kano", "Ibadan"] },
  { c: "Africa", l: "all", q: "What is the capital of Egypt?", a: ["Cairo", "Alexandria", "Giza", "Luxor"] },
  { c: "Africa", l: "all", q: "Which is the most populous country in Africa?", a: ["Nigeria", "Ethiopia", "Egypt", "South Africa"] },
  { c: "Africa", l: "all", q: "The historic city of Timbuktu is in which country?", a: ["Mali", "Niger", "Chad", "Senegal"] },
  { c: "Africa", l: "all", q: "Victoria Falls lies on the border of which two countries?", a: ["Zambia and Zimbabwe", "Kenya and Tanzania", "Angola and Namibia", "Uganda and Rwanda"] },
  { c: "Africa", l: "all", q: "Which large island country lies off Africa's south-east coast?", a: ["Madagascar", "Sri Lanka", "Cuba", "Iceland"] },
  { c: "Africa", l: "all", q: "Nelson Mandela became president of which country?", a: ["South Africa", "Kenya", "Zimbabwe", "Namibia"] },
  { c: "Africa", l: "all", q: "Which sea lies along the north coast of Africa?", a: ["The Mediterranean Sea", "The Red Sea", "The Arabian Sea", "The Caspian Sea"] },
  { c: "Africa", l: "adults", q: "Which is the largest country in Africa by area?", a: ["Algeria", "DR Congo", "Sudan", "Libya"] },
  { c: "Africa", l: "adults", q: "The African Union has its headquarters in which city?", a: ["Addis Ababa", "Nairobi", "Accra", "Cairo"] },
  { c: "Africa", l: "adults", q: "What is the capital of Morocco?", a: ["Rabat", "Casablanca", "Marrakesh", "Tangier"] },
  { c: "Africa", l: "adults", q: "The Serengeti, famous for its wildebeest migration, is mostly in which country?", a: ["Tanzania", "Botswana", "Ghana", "Namibia"] },
  { c: "Africa", l: "adults", q: "What is the currency of South Africa?", a: ["The rand", "The naira", "The cedi", "The shilling"] },
  { c: "Africa", l: "adults", q: "Which African lake is the largest by area?", a: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"] },

  // ---------------------------------------------------------------- World
  { c: "World", l: "kids", q: "How many days are there in a week?", a: ["7", "5", "6", "10"] },
  { c: "World", l: "kids", q: "What colour do you get by mixing blue and yellow?", a: ["Green", "Purple", "Orange", "Brown"] },
  { c: "World", l: "kids", q: "Which planet is called the Red Planet?", a: ["Mars", "Venus", "Jupiter", "Saturn"] },
  { c: "World", l: "kids", q: "How many legs does a spider have?", a: ["8", "6", "10", "4"] },
  { c: "World", l: "kids", q: "What do bees make?", a: ["Honey", "Milk", "Butter", "Jam"] },
  { c: "World", l: "kids", q: "How many sides does a triangle have?", a: ["3", "4", "5", "6"] },
  { c: "World", l: "kids", q: "How many colours are in a rainbow?", a: ["7", "5", "6", "9"] },
  { c: "World", l: "kids", q: "Which animal says “moo”?", a: ["Cow", "Sheep", "Duck", "Dog"] },
  { c: "World", l: "kids", q: "Which is the biggest planet in our solar system?", a: ["Jupiter", "Earth", "Mars", "Neptune"] },
  { c: "World", l: "kids", q: "What do plants need to grow, besides soil?", a: ["Water and sunlight", "Sugar and salt", "Music", "Plastic"] },
  { c: "World", l: "kids", q: "How many months are there in a year?", a: ["12", "10", "11", "13"] },
  { c: "World", l: "kids", q: "Which is the biggest animal in the ocean?", a: ["Blue whale", "Shark", "Octopus", "Dolphin"] },
  { c: "World", l: "all", q: "Which is the largest ocean?", a: ["The Pacific", "The Atlantic", "The Indian", "The Arctic"] },
  { c: "World", l: "all", q: "How many continents are there?", a: ["7", "5", "6", "8"] },
  { c: "World", l: "all", q: "Which gas do plants take in from the air?", a: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"] },
  { c: "World", l: "all", q: "What is the largest organ of the human body?", a: ["The skin", "The liver", "The brain", "The heart"] },
  { c: "World", l: "all", q: "Which planet is closest to the Sun?", a: ["Mercury", "Venus", "Earth", "Mars"] },
  { c: "World", l: "all", q: "What is 12 × 12?", a: ["144", "124", "132", "148"] },
  { c: "World", l: "all", q: "Who painted the Mona Lisa?", a: ["Leonardo da Vinci", "Michelangelo", "Vincent van Gogh", "Pablo Picasso"] },
  { c: "World", l: "all", q: "At what temperature does water boil at sea level?", a: ["100 °C", "90 °C", "80 °C", "120 °C"] },
  { c: "World", l: "adults", q: "What is the chemical symbol for gold?", a: ["Au", "Ag", "Gd", "Go"] },
  { c: "World", l: "adults", q: "In which year did the Second World War end?", a: ["1945", "1939", "1950", "1918"] },
  { c: "World", l: "adults", q: "Who wrote “Romeo and Juliet”?", a: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Chinua Achebe"] },
  { c: "World", l: "adults", q: "What is the capital of Australia?", a: ["Canberra", "Sydney", "Melbourne", "Perth"] },
  { c: "World", l: "adults", q: "Roughly how fast does light travel?", a: ["300,000 km per second", "3,000 km per second", "30,000 km per second", "3 million km per second"] },
  { c: "World", l: "adults", q: "Which element has the atomic number 1?", a: ["Hydrogen", "Helium", "Oxygen", "Carbon"] },
  { c: "World", l: "adults", q: "How many bones are in an adult human body?", a: ["206", "186", "226", "256"] },
  { c: "World", l: "adults", q: "Who developed the theory of general relativity?", a: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Galileo Galilei"] },
  { c: "World", l: "adults", q: "The Great Barrier Reef lies off the coast of which country?", a: ["Australia", "Brazil", "Indonesia", "Mexico"] },
  { c: "World", l: "adults", q: "Which language has the most native speakers worldwide?", a: ["Mandarin Chinese", "English", "Spanish", "Hindi"] },
];
